# Generated by Django 3.2.5 on 2021-09-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0003_auto_20210908_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('gene_len', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genomes',
            fields=[
                ('genome_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('organism_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Pfams',
            fields=[
                ('pfam_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('pfam_name', models.CharField(max_length=264, unique=True)),
                ('pfam_len', models.IntegerField()),
                ('toxic_id', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PfamsInGenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_start', models.IntegerField()),
                ('pfam_end', models.IntegerField()),
                ('bit_score', models.FloatField()),
                ('e_val', models.CharField(max_length=264)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.genes')),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.pfams')),
            ],
        ),
        migrations.AddField(
            model_name='genes',
            name='genome_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.genomes'),
        ),
    ]
