# Generated by Django 3.2.5 on 2021-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfams',
            name='pfam_name',
            field=models.CharField(max_length=264),
        ),
    ]
