# Generated by Django 3.2.5 on 2021-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_pfams_pfam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfams',
            name='toxic_id',
            field=models.CharField(max_length=264),
        ),
    ]
