# Generated by Django 3.2.5 on 2021-09-08 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210908_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfamsingenes',
            name='organism_name',
            field=models.CharField(default=6, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pfamsingenes',
            name='toxic_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
    ]
