# Generated by Django 3.2.5 on 2021-10-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0010_auto_20211012_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('scaffold', models.CharField(max_length=264)),
                ('gene_len', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('product_name', models.CharField(max_length=264)),
                ('protein_toxicity', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Genomes',
            fields=[
                ('genome_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('organism_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Pfams',
            fields=[
                ('pfam_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('pfam_name', models.CharField(max_length=264)),
                ('pfam_len', models.IntegerField()),
                ('toxic_id', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='PfamsInGenes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organism_name', models.CharField(max_length=264)),
                ('toxic_id', models.CharField(max_length=264)),
                ('pfam_start', models.IntegerField()),
                ('pfam_end', models.IntegerField()),
                ('bit_score', models.FloatField()),
                ('e_val', models.CharField(max_length=264)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.genes')),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.pfams')),
            ],
        ),
    ]
