# Generated by Django 3.2.5 on 2021-10-12 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20211012_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='genes',
            name='genome_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='first_app.genomes'),
            preserve_default=False,
        ),
    ]
